/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.carlosaltan.vistas;

import javax.swing.JOptionPane;
import org.carlosaltan.modelo.ModeloUsuario;

/**
 *JFrame donde se hace la vista grafica Principal
 * @author Carlos Altán
 * @version 1.0
 */
public class InicioTiendaAdmin extends javax.swing.JFrame {

    private static VistaProducto instanciaCompra  = null; 
    private static VistaCliente instanCliente = null; 
    private static VerClientes instanciaVerCli = null; 
    private static VerToClientes instanciaVerToClientesTo = null; 
    
    /**
     * Creates new form InicioVeterinaria
     */
    public InicioTiendaAdmin() {
       
        initComponents();
          lookAndFeel(); 
        setLocationRelativeTo(null);
        
        
    }
    /**
     * Metodod Instancia de producto
     * @return retorna la instancia de producto 
     */
    private synchronized VistaProducto getInstanciaProduc(){
        if (instanciaCompra == null){
            instanciaCompra = new VistaProducto();  
           instanciaCompra.setVisible(true);
           jEscritorioPrin.add(instanciaCompra);
        }else if (instanciaCompra.isVisible() == false){
            instanciaCompra.setVisible(true);
          
        }
        instanciaCompra.show();
        return instanciaCompra; 
    }
    /**
     * Metodo instancia de cliente
     * @return  instancia cliente
     */
    private synchronized VistaCliente getInstanciaCliente(){
        if (instanCliente == null){
            instanCliente = new VistaCliente();  
           instanCliente.setVisible(true);
           jEscritorioPrin.add(instanCliente);
        }else if (instanCliente.isVisible() == false){
            instanCliente.setVisible(true);
        //    jEscritorioPrin.add(instanciaDoctor); 
        }
        instanCliente.show();
        return instanCliente; 
    }
    /**
     * metodo con instancia de ver cli 
     * @return instanciaVerCli
     */
    private synchronized VerClientes getInstanciaVerCli(){
        if (instanciaVerCli == null){
            instanciaVerCli = new VerClientes();  
           instanciaVerCli.setVisible(true);
           jEscritorioPrin.add(instanciaVerCli);
        }else if (instanciaVerCli.isVisible() == false){
            instanciaVerCli.setVisible(true);
          
        }
        instanciaVerCli.show();
        return instanciaVerCli; 
    }
    /**
     * Metod para instancia verToclientes
     * @return verToclientes
     */
      private synchronized VerToClientes getInstanciaVerToclientes(){
        if (instanciaVerToClientesTo == null){
            instanciaVerToClientesTo = new VerToClientes();  
           instanciaVerToClientesTo.setVisible(true);
           jEscritorioPrin.add(instanciaVerToClientesTo);
        }else if (instanciaVerToClientesTo.isVisible() == false){
            instanciaVerToClientesTo.setVisible(true);
          
        }
        instanciaVerToClientesTo.show();
        return instanciaVerToClientesTo; 
    }
  
    
    
    public void lookAndFeel(){
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioTiendaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioTiendaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioTiendaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioTiendaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEscritorioPrin = new javax.swing.JDesktopPane();
        back = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jEscritorioPrin.setBackground(new java.awt.Color(0, 204, 204));

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jEscritorioPrin.setLayer(back, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jEscritorioPrinLayout = new javax.swing.GroupLayout(jEscritorioPrin);
        jEscritorioPrin.setLayout(jEscritorioPrinLayout);
        jEscritorioPrinLayout.setHorizontalGroup(
            jEscritorioPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEscritorioPrinLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(back)
                .addContainerGap(1224, Short.MAX_VALUE))
        );
        jEscritorioPrinLayout.setVerticalGroup(
            jEscritorioPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEscritorioPrinLayout.createSequentialGroup()
                .addContainerGap(660, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(39, 39, 39))
        );

        jMenu1.setText("Accesos");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Producto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Cliente");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Buscar Clientes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Ver Clientes");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEscritorioPrin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jEscritorioPrin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
      Login login = new Login(); 
        this.dispose();
            login.setVisible(true);
            login.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_backActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      getInstanciaProduc(); 
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
       
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
          getInstanciaCliente(); 
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        getInstanciaVerCli(); 
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        getInstanciaVerToclientes(); 
    }//GEN-LAST:event_jMenuItem4ActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JDesktopPane jEscritorioPrin;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}
