/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.carlosaltan.vistas;

import javax.swing.JOptionPane;
import org.carlosaltan.controlador.ControlUsuario;
import org.carlosaltan.modelo.ModeloUsuario;


/**
 *
 * @author Carlos Altán
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
  
    public Login() {
        initComponents();
    }
    
    ControlUsuario controlador = new ControlUsuario(); 
    private void VentanaAdmin(){
        InicioTiendaAdmin vet = new InicioTiendaAdmin ();
        vet.setVisible(true);
        vet.setLocationRelativeTo(null);
    }
    private void VentanaCli(){
        InicioTiendaCliente vet = new InicioTiendaCliente ();
        vet.setVisible(true);
        vet.setLocationRelativeTo(null);
    }
    private void VentanaAgregar(){
        InsertarCliente mi = new InsertarCliente(); 
        mi.setVisible(true);
        mi.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Crear Usuario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 131, -1));

        jButton3.setText("Iniciar Sesion");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        jLabel1.setText("User");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel2.setText("Contraseña");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 126, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 340, 180));

        jLabel4.setFont(new java.awt.Font("Impact", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MUNDO GEEK");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 290, 170));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/carlosaltan/recursos/ima laptop pr.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       ModeloUsuario usuario = new ModeloUsuario();
      usuario.setUsuario(txtUsuario.getText()); 
      usuario.setContrasena(String.valueOf(jPasswordField1.getPassword()));
        if (controlador.iniciarSesionCliente(usuario) == true) {
            JOptionPane.showMessageDialog(null, "Bienvenido " + usuario.getUsuario());
            VentanaCli();
            txtUsuario.setText("");
            jPasswordField1.setText("");
            this.dispose();   
        }else if( controlador.iniciarSesionAdmin(usuario) == true){
           JOptionPane.showMessageDialog(null, "Bienvenido " + usuario.getUsuario());
           VentanaAdmin();
           txtUsuario.setText("");
           jPasswordField1.setText("");
           this.dispose();

        }else{
            JOptionPane.showMessageDialog(null, "LOGIN INCORRECTO, VERIFIQUE LOS DAROS ;(" + usuario.getUsuario());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        VentanaAgregar();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

   
}
